import { Chapter } from "./types";

export const chapters: Chapter[] = [
  {
    id: 0,
    slug: "introduction",
    label: "Introduction",
    title: "The Rigged Game",
    summary: "The modern environment isn't neutral: it's weaponized against depth. Algorithms reward reactivity over focus. Economics reward speed over patience. Culture rewards signaling over building.",
    verses: [
      "The modern environment isn't neutral: it's weaponized against depth.",
      "If you're trying to make something real over multiple years, you're fighting infrastructure designed to make you quit.",
      "Most people quit not because they lack talent, but because they lack survival principles for hostile conditions.",
      "Mastery survives only when supported by deliberate, structural countermeasures.",
    ],
    themes: "rigged system, survival principles, structural countermeasures",
    visualizationDescription: "A soft, slowly emerging grid or waveform representing the signal cutting through 21st century noise.",
    artifactId: "introduction",
    narrative: "A brief personal note: Transitioning out of a rigid, disciplined environment into a world engineered for drift revealed just how hostile the modern landscape is to long-term craft. The contrast was immediate and clarifying. What felt possible under one set of conditions became nearly impossible under another, not because capability changed, but because the environment did. Ancient Japanese craft principles offered a counterweight: not inspiration, but infrastructure. Systems that functioned as survival mechanisms for people doing hard work over decades when everything pushed them to quit.",
  },
  {
    id: 1,
    slug: "do",
    label: "01",
    title: "Dō (道): Committing to the Path",
    summary: "The existential first step: choosing a path before certainty, before clarity, and before evidence. Why commitment precedes passion, not the other way around.",
    verses: [
      "Commitment before certainty. Choosing the path before evidence arrives.",
      "The existential first step: choosing a path before certainty, before clarity, and before evidence.",
      "Why commitment precedes passion, not the other way around.",
      "What it means to shift from 'exploring' to 'walking,' and why nothing else in the system functions until you do.",
    ],
    themes: "commitment, path, certainty, passion",
    visualizationDescription: "A path emerging from uncertainty, commitment taking form before clarity arrives.",
    artifactId: "do",
    partId: 1,
  },
  {
    id: 2,
    slug: "wabi-sabi",
    label: "02",
    title: "Wabi-Sabi (侘寂): Starting Crude",
    summary: "The antidote to perfectionism in a world where every beginner attempt is permanent and public. Why imperfect beginnings are the only gateway to refined work.",
    verses: [
      "Beauty in Imperfection: Starting crude when everything is permanent and public.",
      "The antidote to perfectionism in a world where every beginner attempt is permanent and public.",
      "Why imperfect beginnings are the only gateway to refined work.",
      "How to embrace visible flaws as proof of progress, not evidence of inadequacy.",
    ],
    themes: "imperfection, transience, acceptance of flaws, beginnings",
    visualizationDescription: "Imperfect form that cracks or erodes over time and is subtly re-emphasized, turning flaws into features.",
    artifactId: "wabi-sabi",
    partId: 1,
  },
  {
    id: 3,
    slug: "kaizen",
    label: "03",
    title: "Kaizen (改善): Method Before Meaning",
    summary: "Why meaning doesn't appear at the beginning of a craft. The early months often feel hollow, mechanical, and uncertain. Kaizen (continuous, marginal improvement) builds competence first, and meaning grows from competence, not inspiration.",
    verses: [
      "Method before meaning. Building competence when passion hasn't arrived yet.",
      "Why meaning doesn't appear at the beginning of a craft.",
      "The early months often feel hollow, mechanical, and uncertain.",
      "Continuous, marginal improvement builds competence first, and meaning grows from competence, not inspiration.",
    ],
    themes: "continuous improvement, method, competence, meaning",
    visualizationDescription: "Incremental progress visualized as small, consistent steps building upward.",
    artifactId: "kaizen",
    partId: 2,
  },
  {
    id: 4,
    slug: "shokunin",
    label: "04",
    title: "Shokunin (職人): Becoming the Craftsperson",
    summary: "When the plateau arrives, improvement slows, and external validation fades, identity becomes the load-bearing structure. Shokunin reframes the work from transaction to vocation: you do the work because you are a craftsperson, not because outcomes arrived on time.",
    verses: [
      "Identity as load-bearing structure when external validation disappears.",
      "When the plateau arrives, improvement slows, and external validation fades.",
      "Identity becomes the load-bearing structure.",
      "You do the work because you are a craftsperson, not because outcomes arrived on time.",
    ],
    themes: "craftsmanship, dedication, identity, vocation",
    visualizationDescription: "Rows of simple workpieces that grow more refined with each iteration.",
    artifactId: "shokunin",
    partId: 2,
  },
  {
    id: 5,
    slug: "ma",
    label: "05",
    title: "Ma (間): Strategic Emptiness",
    summary: "The middle years demand rest as infrastructure, not reward. Productivity culture monetizes constant output. Algorithms punish gaps. Economics makes rest feel unaffordable. Ma counters all of this by making emptiness non-negotiable: the structural pause that prevents burnout before it arrives.",
    verses: [
      "Rest as infrastructure, not reward. Preventing the burnout cascade.",
      "The middle years demand rest as infrastructure, not reward.",
      "Productivity culture monetizes constant output. Algorithms punish gaps. Economics makes rest feel unaffordable.",
      "Ma counters all of this by making emptiness non-negotiable: the structural pause that prevents burnout before it arrives.",
    ],
    themes: "rest, emptiness, burnout prevention, strategic pause",
    visualizationDescription: "Negative space and pauses visualized as essential structural elements.",
    artifactId: "ma",
    partId: 3,
  },
  {
    id: 6,
    slug: "ganbaru",
    label: "06",
    title: "Ganbaru (頑張る): Relentless Continuation",
    summary: "Rest prevents burnout, but it doesn't solve motivation collapse. Ganbaru provides continuation practices for when showing up feels impossible. Not inspiration or discipline: minimum viable presence. The systems that keep you on the path when every rational signal says quit.",
    verses: [
      "Showing up when motivation is permanently gone and discipline isn't enough.",
      "Rest prevents burnout, but it doesn't solve motivation collapse.",
      "Ganbaru provides continuation practices for when showing up feels impossible.",
      "Not inspiration or discipline: minimum viable presence. The systems that keep you on the path when every rational signal says quit.",
    ],
    themes: "persistence, continuation, showing up, minimum viable presence",
    visualizationDescription: "Steady, unbroken continuity despite obstacles and resistance.",
    artifactId: "ganbaru",
    partId: 3,
  },
  {
    id: 7,
    slug: "fudoshin",
    label: "07",
    title: "Fudōshin (不動心): Immovable Mind",
    summary: "The age of information abundance creates algorithmic FOMO: endless comparisons, constant opportunities, a thousand alternative paths. Fudōshin is centered clarity: the ability to see noise without reacting to it, and to hold your path steady without becoming rigid or blind.",
    verses: [
      "Centered clarity amid algorithmic noise and constant comparison.",
      "The age of information abundance creates algorithmic FOMO: endless comparisons, constant opportunities, a thousand alternative paths.",
      "Fudōshin is centered clarity: the ability to see noise without reacting to it.",
      "Hold your path steady without becoming rigid or blind.",
    ],
    themes: "clarity, focus, noise, centeredness",
    visualizationDescription: "A calm center point surrounded by chaotic noise that doesn't affect the core.",
    artifactId: "fudoshin",
    partId: 3,
  },
  {
    id: 8,
    slug: "shibumi",
    label: "08",
    title: "Shibumi (渋み): Simplicity After Complexity",
    summary: "Years into a craft, capability becomes a trap. You can add complexity, ornamentation, and sophistication far beyond what the work actually needs. Shibumi is refined simplicity: the quiet form that remains after unnecessary complexity is removed. The essence becomes visible only after mastery.",
    verses: [
      "Simplicity after complexity. Refinement through subtraction, not addition.",
      "Years into a craft, capability becomes a trap.",
      "You can add complexity, ornamentation, and sophistication far beyond what the work actually needs.",
      "Shibumi is refined simplicity: the quiet form that remains after unnecessary complexity is removed. The essence becomes visible only after mastery.",
    ],
    themes: "simplicity, refinement, subtraction, essence",
    visualizationDescription: "Complexity gradually refined away to reveal essential form.",
    artifactId: "shibumi",
    partId: 4,
  },
  {
    id: 9,
    slug: "mushin",
    label: "09",
    title: "Mushin (無心): When the Ground Shifts",
    summary: "The conditions of the craft eventually change: markets, platforms, tools, technologies, cultural values. Mushin is the state of non-attachment that lets you evolve without losing your core. Adaptation without starting from zero. Carrying principles forward when the specific form can no longer hold.",
    verses: [
      "Adaptive Flow: Carrying principles forward when the ground shifts and the craft itself changes.",
      "The conditions of the craft eventually change: markets, platforms, tools, technologies, cultural values.",
      "Mushin is the state of non-attachment that lets you evolve without losing your core.",
      "Adaptation without starting from zero. Carrying principles forward when the specific form can no longer hold.",
    ],
    themes: "adaptation, non-attachment, evolution, principles",
    visualizationDescription: "Fluid transformation maintaining core structure while adapting to new forms.",
    artifactId: "mushin",
    partId: 5,
  },
  {
    id: 10,
    slug: "conclusion",
    label: "Conclusion",
    title: "The System, Not the Talent",
    summary: "A synthesis: the nine principles form a sequential defense against the structural quitting points built into modern life. Mastery isn't a product of talent, it's the result of survival. The craftsman isn't the gifted one; they're the one who stayed in the game.",
    verses: [
      "The nine principles form a sequential defense against the structural quitting points built into modern life.",
      "Mastery isn't a product of talent, it's the result of survival.",
      "The craftsman isn't the gifted one; they're the one who stayed in the game.",
      "The obstacles are the filter. The system is rigged so that only people with systematic approaches to persistence can build anything real.",
      "These principles are infrastructure for staying in the game when everything pushes you out.",
      "Not because you're naturally gifted.",
      "Because you did the work.",
    ],
    themes: "synthesis, survival, persistence, infrastructure",
    visualizationDescription: "Integrative pattern that hints at all previous motifs, quietly unified.",
    artifactId: "conclusion",
  },
];
